// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcxeWsqrAXXu4mVPSyjSjFSRAZ_4RODpU',
    appId: '1:132262039095:web:a5013015c2d3dc75d639b2',
    messagingSenderId: '132262039095',
    projectId: 'fir-login-cff25',
    authDomain: 'fir-login-cff25.firebaseapp.com',
    storageBucket: 'fir-login-cff25.firebasestorage.app',
    measurementId: 'G-985LV8MDJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzjeI7OF2qnIJT1Co6FMwDTCbLuIRiMc',
    appId: '1:132262039095:android:b62066a0e54a35acd639b2',
    messagingSenderId: '132262039095',
    projectId: 'fir-login-cff25',
    storageBucket: 'fir-login-cff25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepY28zMeQjaiwb34xmpAgcJuhr1SUGbE',
    appId: '1:132262039095:ios:ea6cdd04fa23dfedd639b2',
    messagingSenderId: '132262039095',
    projectId: 'fir-login-cff25',
    storageBucket: 'fir-login-cff25.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEmailPassAuthAndUidSaveLocalDatabaseee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepY28zMeQjaiwb34xmpAgcJuhr1SUGbE',
    appId: '1:132262039095:ios:ea6cdd04fa23dfedd639b2',
    messagingSenderId: '132262039095',
    projectId: 'fir-login-cff25',
    storageBucket: 'fir-login-cff25.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEmailPassAuthAndUidSaveLocalDatabaseee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcxeWsqrAXXu4mVPSyjSjFSRAZ_4RODpU',
    appId: '1:132262039095:web:45e849775b6552d4d639b2',
    messagingSenderId: '132262039095',
    projectId: 'fir-login-cff25',
    authDomain: 'fir-login-cff25.firebaseapp.com',
    storageBucket: 'fir-login-cff25.firebasestorage.app',
    measurementId: 'G-WXZPBDCFNY',
  );
}
